# Generated by Django 4.2.16 on 2024-10-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='receive_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
