# Generated by Django 4.2.16 on 2024-11-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_comment_dislike_remove_comment_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dislike_users',
            new_name='disliked_users',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='like_users',
            new_name='liked_users',
        ),
        migrations.RemoveField(
            model_name='question',
            name='dislike_users',
        ),
        migrations.RemoveField(
            model_name='question',
            name='like_users',
        ),
    ]
