# Generated by Django 4.2.16 on 2024-11-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_tag_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='questions.tag'),
        ),
    ]
