# Generated by Django 4.2.16 on 2024-11-25 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0006_alter_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
